version: "3"

services:
  app:
    container_name: app_apache
    build: 
      context: ./compose/apache
      dockerfile: Dockerfile
    ports:
      - "8000:80"  

  #web_front:
  #  container_name: vue_web_front
  #  build: ./compose/vuecli
  #  command: sh +x yarn-install-start.sh
  #  volumes: 
  #    - ./src/vuecli:/code
  #  ports:
  #    - 8080:8080
  #  env_file: 
  #    - ./.envs/.vuecli
  #  tty: true
    
  web_backend:
    container_name: django_web_backend
    build: ./compose/django
    #command: bash -c "./setup/wait-for-it.sh db:3306 && sh /setup/createBD.sh"
    command: sh +x /setup/createBD.sh
    volumes: 
      - ./src/django:/code
    ports:
      - 3001:3000
    env_file: 
      - ./.envs/.django
    tty: true
    depends_on:
      - db

  db:
    container_name: mysql
    build: ./compose/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes: 
      - ./db:/var/lib/mysql
      - ./compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      TZ: 'Asia/Tokyo' 
    env_file:
      - ./.envs/.mysql
    ports:
      - 3306:3306
    #env_file: 
    #  - ./.envs/.django
    #tty: true