version: "3"

services: 
  web_front:
    container_name: vue_web_front
    build: ./compose/vuecli
    command: sh +x yarn-install-start.sh
    volumes: 
      - ./src/vuecli:/code
    ports:
      - 8081:8080
    env_file: 
      - ./.envs/.vuecli
    tty: true
    
  web_backend:
    container_name: django_web_backend
    build: ./compose/django
    command: sh +x /setup/createBD.sh
    volumes: 
      - ./src/django:/code
    ports:
      - 3001:3000
    env_file: 
      - ./.envs/.django
    tty: true